const { HttpError } = require('../core/http');
const ORDER = { CRITICAL: 0, ATTENTION: 1, OK: 2 };
function allowedRows(snapshot, user) { if (user.role !== 'coordinator') return snapshot.rows; const scope = new Set(user.courseIds.map(String)); return snapshot.rows.filter((row) => scope.has(row.course.id)); }
function summarize(rows) {
  const teachers = new Set(); const courses = new Set(); const access = new Map(); const requirements = { total: rows.length, pending: 0, overdue: 0, deliveredLate: 0, deliveredOnTime: 0, inheritedReady: 0, notVerifiable: 0 };
  for (const row of rows) { teachers.add(row.teacher.id); courses.add(row.course.id); access.set(`${row.course.id}:${row.teacher.id}`, row.accessStatus); if (row.structureStatus === 'PENDING') requirements.pending += 1; if (row.structureStatus === 'PENDING' && row.overdue) requirements.overdue += 1; if (row.structureStatus === 'DELIVERED_LATE') requirements.deliveredLate += 1; if (row.structureStatus === 'DELIVERED_ON_TIME') requirements.deliveredOnTime += 1; if (row.structureStatus === 'INHERITED_READY') requirements.inheritedReady += 1; if (row.structureStatus === 'NOT_VERIFIABLE') requirements.notVerifiable += 1; }
  const accessSummary = { current: 0, attention: 0, critical: 0, never: 0, outsideWindow: 0 };
  for (const status of access.values()) { if (status === 'CURRENT') accessSummary.current += 1; if (status === 'ATTENTION') accessSummary.attention += 1; if (status === 'CRITICAL') accessSummary.critical += 1; if (status === 'NEVER') accessSummary.never += 1; if (status === 'OUTSIDE_WINDOW') accessSummary.outsideWindow += 1; }
  return { monitoredTeachers: teachers.size, courses: courses.size, requirements, access: accessSummary };
}
function groupAssignments(rows) {
  const groups = new Map();
  for (const row of rows) { const key = `${row.course.id}:${row.teacher.id}`; const group = groups.get(key) || { id: key, course: row.course, teacher: row.teacher, accessStatus: row.accessStatus, lastAccessAt: row.lastAccessAt, daysSinceAccess: row.daysSinceAccess, provenance: row.provenance, requirements: [] }; group.requirements.push({ ...row.requirement, status: row.structureStatus, reasonCode: row.reasonCode, reason: row.reason, overdue: row.overdue, deadlineAt: row.deadlineAt, deadlineSource: row.deadlineSource, configuredAt: row.configuredAt, timingSource: row.timingSource, expectedQuantity: row.expectedQuantity, observedQuantity: row.observedQuantity, evidence: row.evidence }); groups.set(key, group); }
  return [...groups.values()].map((group) => { const critical = group.requirements.find((item) => item.status === 'NOT_VERIFIABLE' || item.status === 'PENDING' && item.overdue); const attention = group.requirements.find((item) => item.status === 'DELIVERED_LATE' || item.status === 'PENDING'); const accessCritical = ['CRITICAL', 'NEVER'].includes(group.accessStatus); const accessAttention = group.accessStatus === 'ATTENTION'; const severity = accessCritical || critical ? 'CRITICAL' : accessAttention || attention ? 'ATTENTION' : 'OK'; const issueCount = group.requirements.filter((item) => ['NOT_VERIFIABLE', 'DELIVERED_LATE', 'PENDING'].includes(item.status)).length; const primaryReason = critical?.reason || (accessCritical ? group.accessStatus === 'NEVER' ? 'Nenhum acesso registrado no período ativo.' : `Último acesso há ${group.daysSinceAccess} dias.` : null) || attention?.reason || (accessAttention ? `Último acesso há ${group.daysSinceAccess} dias.` : 'Sem pendências identificadas.'); return { ...group, severity, issueCount, primaryReason }; });
}
function filterRows(rows, filters) { const query = String(filters.query || '').trim().toLocaleLowerCase('pt-BR'); const statuses = new Set(String(filters.status || '').split(',').filter(Boolean)); return rows.filter((row) => !(filters.period && row.course.period !== filters.period) && !(filters.modality && row.course.modality !== filters.modality) && !(filters.courseId && row.course.id !== String(filters.courseId)) && !(query && !`${row.course.name} ${row.course.shortName} ${row.teacher.name}`.toLocaleLowerCase('pt-BR').includes(query)) && !(statuses.size && !statuses.has(row.structureStatus) && !statuses.has(row.accessStatus))); }
function scopedIssues(snapshot, user) { if (user.role !== 'coordinator') return snapshot.qualityIssues; const scope = new Set(user.courseIds.map(String)); return snapshot.qualityIssues.filter((issue) => !issue.courseId || scope.has(String(issue.courseId))); }
function filterOptions(rows) { const unique = (values) => [...new Set(values)].sort((a, b) => a.localeCompare(b, 'pt-BR')); return { periods: unique(rows.map((row) => row.course.period)), modalities: unique(rows.map((row) => row.course.modality)).map((value) => ({ value, label: rows.find((row) => row.course.modality === value).course.modalityLabel })), courses: [...new Map(rows.map((row) => [row.course.id, { value: row.course.id, label: row.course.shortName }])).values()].sort((a, b) => a.label.localeCompare(b.label, 'pt-BR')) }; }
function modalityBreakdown(rows) { const map = new Map(); for (const row of rows) { const group = map.get(row.course.modality) || { modality: row.course.modality, label: row.course.modalityLabel, total: 0, issues: 0 }; group.total += 1; if (row.structureStatus === 'NOT_VERIFIABLE' || row.structureStatus === 'DELIVERED_LATE' || row.structureStatus === 'PENDING' && row.overdue) group.issues += 1; map.set(row.course.modality, group); } return [...map.values()].map((item) => ({ ...item, compliant: item.total - item.issues })); }
class DashboardService {
  constructor({ store, snapshotIntervalMinutes }) { this.store = store; this.snapshotIntervalMinutes = snapshotIntervalMinutes; }
  async getDashboard(user, filters = {}) {
    const snapshot = await this.store.latestSnapshot(); if (!snapshot) throw new HttpError(503, 'SNAPSHOT_UNAVAILABLE', 'Ainda não há coleta disponível.');
    const scoped = allowedRows(snapshot, user); const filtered = filterRows(scoped, filters); const assignments = groupAssignments(filtered).sort((a, b) => ORDER[a.severity] - ORDER[b.severity] || (b.daysSinceAccess ?? -1) - (a.daysSinceAccess ?? -1) || a.course.shortName.localeCompare(b.course.shortName, 'pt-BR'));
    const page = Math.max(1, Number(filters.page) || 1); const pageSize = Math.max(5, Math.min(Number(filters.pageSize) || 20, 50)); const history = await this.store.listSnapshots(8);
    const trend = history.reverse().map((item) => { const historical = groupAssignments(allowedRows(item, user)); return { generatedAt: item.generatedAt, critical: historical.filter((x) => x.severity === 'CRITICAL').length, attention: historical.filter((x) => x.severity === 'ATTENTION').length }; });
    const issues = scopedIssues(snapshot, user); const ageMinutes = Math.floor((Date.now() - new Date(snapshot.generatedAt)) / 60000);
    return { meta: { snapshotId: snapshot.id, generatedAt: snapshot.generatedAt, source: snapshot.source, isDemo: snapshot.isDemo, rulesVersion: snapshot.rulesVersion, rulesStatus: snapshot.rulesStatus, qualityStatus: issues.some((issue) => issue.severity === 'CRITICAL') ? 'BLOCKED' : snapshot.qualityStatus, publishAllowed: snapshot.publishAllowed, stale: ageMinutes > this.snapshotIntervalMinutes * 2, qualityIssues: issues }, summary: summarize(filtered), trend, modalityBreakdown: modalityBreakdown(filtered), rows: assignments.slice((page - 1) * pageSize, page * pageSize), filters: filterOptions(scoped), pagination: { page, pageSize, total: assignments.length, pages: Math.max(1, Math.ceil(assignments.length / pageSize)) } };
  }
}
module.exports = { DashboardService, allowedRows, groupAssignments, summarize };
