version: '3.8'

services:
  # Serviço do Frontend (React App + Nginx)
  frontend:
    container_name: disciplinedash-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend-api

  # Serviço do Backend (Node.js API)
  backend-api:
    container_name: disciplinedash-backend-api
    build:
      context: ./backend  # <-- Garanta que esta linha está assim
      dockerfile: Dockerfile      # <-- E esta também
    command: node --openssl-legacy-provider server.js