foreground = yes
debug = 7
output = /tmp/stunnel.log

[mssql-proxy]
client = yes
accept = 127.0.0.1:1434
connect = db.unifenas.br:1433

sslVersion = TLSv1
ciphers = DEFAULT:@SECLEVEL=0

TIMEOUTconnect = 30
TIMEOUTclose = 10
verify = 0
